before_install:
  - curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.1-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.7.1-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - sleep 10
script: coverage run -m unittest mlbridge_middleware/tests/test_middleware.py
after_success:
  - bash <(curl -s https://codecov.io/bash)